name: deploy

on: 
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v1

        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: 3.x

        - name: Install pelican with markdown
          shell: bash
          run: "pip install invoke pelican[markdown]"

        - name: Build the project
          shell: bash
          run: "pelican . -s ./settings/settings_prod.py"

        - name: Copy output via scp
          uses: appleboy/scp-action@master
          with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USER }}
              port: ${{ secrets.PORT }}
              key: ${{ secrets.SSHKEY }}
              source: "settings/output/PROD/"
              target: ${{ secrets.TARGET_PATH }}
              strip_components: 1